name: CI Workflow

on:
  pull_request:
    branches: 
      - "main"  # Se ejecutará cuando haya un PR hacia la rama main.
      - "dev"   # Se ejecutará también cuando haya un PR hacia la rama dev.

jobs:
  build:
    runs-on: ubuntu-latest  # El entorno de ejecución para el job 'build'.
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Para clonar el repositorio.
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Compile with Maven
      run: mvn clean compile  # Solo ejecuta la fase de compilación.

  test:
    runs-on: ubuntu-latest  # El entorno de ejecución para el job 'test'.
    
    needs: build  # Este job depende del job 'build' para ejecutarse.
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Para clonar el repositorio.
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Verify with Maven
      run: mvn verify  # Ejecuta la fase de verificación, sin necesidad de recompilar.

  deploy:
    runs-on: ubuntu-latest  # El entorno de ejecución para el job 'deploy'.
    
    needs: test  # Este job depende del job 'test' para ejecutarse.
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Para clonar el repositorio.
    
    - name: Azure WebApp Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: "labinfoweb-gxavaxcjgfcxdegg"
        package: "target/ReservasLab-0.0.1-SNAPSHOT.jar"

